sudo: required
language: swift
osx_image: xcode10
rvm:
  - 2.2
before_script:
  - gem install awesome_bot
  - gem install bundler
  - gem install danger
script:
  - awesome_bot applications.json -w https://matrix.org,https://camo.githubusercontent.com
  - danger
after_success:
  - swift ./.github/ReadmeGenerator.swift
  - chmod +x ./.github/deploy.sh
  - ./.github/deploy.sh
notifications:
  email: true
