sudo: required
language: swift
osx_image: xcode10
rvm:
  - 2.2
before_script:
  - gem install awesome_bot
  - gem install danger
script:
  - awesome_bot applications.json -w https://matrix.org/blog/home/
  - danger
after_success:
  - swift ./.github/ReadmeGenerator.swift
  - ./.github/deploy.sh
notifications:
  email: false